[build]
  functions = "netlify/functions"

[functions]
  included_files = ["src/responses.json"]

[dev]
  functions = "netlify/functions"
  
[security]
  headers = [
    { for = "/*", values = { "X-Frame-Options" = "DENY", "X-XSS-Protection" = "1; mode=block", "Content-Security-Policy" = "frame-ancestors 'none'" } }
  ]
